# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsmt_gui_v1.ui'
#
# Created: Thu Apr  4 13:45:54 2013
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!


from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 817)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 210, 1101, 551))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setBaseSize(QtCore.QSize(200, 200))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.InstructionsTab = QtGui.QWidget()
        self.InstructionsTab.setObjectName("InstructionsTab")
        self.textEditInstructions = QtGui.QTextEdit(self.InstructionsTab)
        self.textEditInstructions.setGeometry(QtCore.QRect(0, 0, 1091, 531))
        self.textEditInstructions.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.textEditInstructions.setObjectName("textEditInstructions")
        self.tabWidget.addTab(self.InstructionsTab, "")
        self.InfoTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoTab.sizePolicy().hasHeightForWidth())
        self.InfoTab.setSizePolicy(sizePolicy)
        self.InfoTab.setObjectName("InfoTab")
        self.layoutWidget = QtGui.QWidget(self.InfoTab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 16, 1041, 420))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelInfo_Mode = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_Mode.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelInfo_Mode.setFont(font)
        self.labelInfo_Mode.setObjectName("labelInfo_Mode")
        self.gridLayout_2.addWidget(self.labelInfo_Mode, 0, 0, 1, 2)
        self.radioButtonInfo_Catalogue = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonInfo_Catalogue.setEnabled(False)
        self.radioButtonInfo_Catalogue.setChecked(True)
        self.radioButtonInfo_Catalogue.setObjectName("radioButtonInfo_Catalogue")
        self.gridLayout_2.addWidget(self.radioButtonInfo_Catalogue, 1, 0, 1, 2)
        self.radioButtonInfo_Manual = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonInfo_Manual.setEnabled(False)
        self.radioButtonInfo_Manual.setObjectName("radioButtonInfo_Manual")
        self.gridLayout_2.addWidget(self.radioButtonInfo_Manual, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.checkBoxInfo_CentroidOn = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxInfo_CentroidOn.setEnabled(False)
        self.checkBoxInfo_CentroidOn.setChecked(True)
        self.checkBoxInfo_CentroidOn.setObjectName("checkBoxInfo_CentroidOn")
        self.gridLayout_2.addWidget(self.checkBoxInfo_CentroidOn, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelInfo_MaskInfo = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelInfo_MaskInfo.setFont(font)
        self.labelInfo_MaskInfo.setObjectName("labelInfo_MaskInfo")
        self.gridLayout_6.addWidget(self.labelInfo_MaskInfo, 0, 0, 1, 1)
        self.labelInfo_ProposalCode = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_ProposalCode.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable)
        self.labelInfo_ProposalCode.setObjectName("labelInfo_ProposalCode")
        self.gridLayout_6.addWidget(self.labelInfo_ProposalCode, 1, 0, 1, 1)
        self.labelInfo_Proposer = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_Proposer.setObjectName("labelInfo_Proposer")
        self.gridLayout_6.addWidget(self.labelInfo_Proposer, 2, 0, 1, 1)
        self.lineEditInfo_Proposer = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditInfo_Proposer.setObjectName("lineEditInfo_Proposer")
        self.gridLayout_6.addWidget(self.lineEditInfo_Proposer, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(600, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 2, 2, 1, 1)
        self.labelInfo_Creator = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_Creator.setObjectName("labelInfo_Creator")
        self.gridLayout_6.addWidget(self.labelInfo_Creator, 3, 0, 1, 1)
        self.lineEditInfo_Creator = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditInfo_Creator.setObjectName("lineEditInfo_Creator")
        self.gridLayout_6.addWidget(self.lineEditInfo_Creator, 3, 1, 1, 1)
        self.lineEditInfo_ProposalCode = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditInfo_ProposalCode.setObjectName("lineEditInfo_ProposalCode")
        self.gridLayout_6.addWidget(self.lineEditInfo_ProposalCode, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.line_5 = QtGui.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.verticalLayoutInfo_RSSSetup = QtGui.QVBoxLayout()
        self.verticalLayoutInfo_RSSSetup.setObjectName("verticalLayoutInfo_RSSSetup")
        self.labelInfo_RSSSetup = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_RSSSetup.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelInfo_RSSSetup.setFont(font)
        self.labelInfo_RSSSetup.setTextFormat(QtCore.Qt.RichText)
        self.labelInfo_RSSSetup.setObjectName("labelInfo_RSSSetup")
        self.verticalLayoutInfo_RSSSetup.addWidget(self.labelInfo_RSSSetup)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelInfo_Filter = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_Filter.setEnabled(False)
        self.labelInfo_Filter.setObjectName("labelInfo_Filter")
        self.gridLayout.addWidget(self.labelInfo_Filter, 0, 0, 1, 1)
        self.comboBoxInfo_Filter = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxInfo_Filter.setEnabled(False)
        self.comboBoxInfo_Filter.setObjectName("comboBoxInfo_Filter")
        self.comboBoxInfo_Filter.addItem("")
        self.comboBoxInfo_Filter.addItem("")
        self.comboBoxInfo_Filter.addItem("")
        self.comboBoxInfo_Filter.addItem("")
        self.comboBoxInfo_Filter.addItem("")
        self.gridLayout.addWidget(self.comboBoxInfo_Filter, 0, 1, 1, 1)
        self.labelInfo_Grating = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_Grating.setEnabled(False)
        self.labelInfo_Grating.setObjectName("labelInfo_Grating")
        self.gridLayout.addWidget(self.labelInfo_Grating, 1, 0, 1, 1)
        self.comboBoxInfo_Grating = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxInfo_Grating.setEnabled(False)
        self.comboBoxInfo_Grating.setObjectName("comboBoxInfo_Grating")
        self.comboBoxInfo_Grating.addItem("")
        self.comboBoxInfo_Grating.addItem("")
        self.comboBoxInfo_Grating.addItem("")
        self.comboBoxInfo_Grating.addItem("")
        self.comboBoxInfo_Grating.addItem("")
        self.comboBoxInfo_Grating.addItem("")
        self.gridLayout.addWidget(self.comboBoxInfo_Grating, 1, 1, 1, 1)
        self.labelInfo_CamAng = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_CamAng.setEnabled(False)
        self.labelInfo_CamAng.setObjectName("labelInfo_CamAng")
        self.gridLayout.addWidget(self.labelInfo_CamAng, 2, 0, 1, 1)
        self.labelInfo_GrAng = QtGui.QLabel(self.layoutWidget)
        self.labelInfo_GrAng.setEnabled(False)
        self.labelInfo_GrAng.setObjectName("labelInfo_GrAng")
        self.gridLayout.addWidget(self.labelInfo_GrAng, 3, 0, 1, 1)
        self.horizontalSliderInfo_CamAng = QtGui.QSlider(self.layoutWidget)
        self.horizontalSliderInfo_CamAng.setEnabled(False)
        self.horizontalSliderInfo_CamAng.setSingleStep(2)
        self.horizontalSliderInfo_CamAng.setProperty("value", 1)
        self.horizontalSliderInfo_CamAng.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderInfo_CamAng.setObjectName("horizontalSliderInfo_CamAng")
        self.gridLayout.addWidget(self.horizontalSliderInfo_CamAng, 2, 2, 1, 1)
        self.horizontalSliderInfo_GrAng = QtGui.QSlider(self.layoutWidget)
        self.horizontalSliderInfo_GrAng.setEnabled(False)
        self.horizontalSliderInfo_GrAng.setSingleStep(2)
        self.horizontalSliderInfo_GrAng.setProperty("value", 1)
        self.horizontalSliderInfo_GrAng.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderInfo_GrAng.setObjectName("horizontalSliderInfo_GrAng")
        self.gridLayout.addWidget(self.horizontalSliderInfo_GrAng, 3, 2, 1, 1)
        self.lineEditInfo_CamAng = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditInfo_CamAng.setEnabled(False)
        self.lineEditInfo_CamAng.setReadOnly(True)
        self.lineEditInfo_CamAng.setObjectName("lineEditInfo_CamAng")
        self.gridLayout.addWidget(self.lineEditInfo_CamAng, 2, 1, 1, 1)
        self.lineEditInfo_GrAng = QtGui.QLineEdit(self.layoutWidget)
        self.lineEditInfo_GrAng.setEnabled(False)
        self.lineEditInfo_GrAng.setReadOnly(True)
        self.lineEditInfo_GrAng.setObjectName("lineEditInfo_GrAng")
        self.gridLayout.addWidget(self.lineEditInfo_GrAng, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(600, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.verticalLayoutInfo_RSSSetup.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.verticalLayoutInfo_RSSSetup)
        self.tabWidget.addTab(self.InfoTab, "")
        self.CatTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CatTab.sizePolicy().hasHeightForWidth())
        self.CatTab.setSizePolicy(sizePolicy)
        self.CatTab.setObjectName("CatTab")
        self.labelCat_Infotext = QtGui.QLabel(self.CatTab)
        self.labelCat_Infotext.setGeometry(QtCore.QRect(9, 9, 928, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.labelCat_Infotext.setFont(font)
        self.labelCat_Infotext.setWordWrap(True)
        self.labelCat_Infotext.setObjectName("labelCat_Infotext")
        self.layoutWidget1 = QtGui.QWidget(self.CatTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 1081, 491))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.toolButtonCat_Load = QtGui.QToolButton(self.layoutWidget1)
        self.toolButtonCat_Load.setEnabled(False)
        self.toolButtonCat_Load.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.toolButtonCat_Load.setObjectName("toolButtonCat_Load")
        self.gridLayout_5.addWidget(self.toolButtonCat_Load, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 1, 1, 1)
        self.pushButtonCat_AddSlits = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonCat_AddSlits.setObjectName("pushButtonCat_AddSlits")
        self.gridLayout_5.addWidget(self.pushButtonCat_AddSlits, 0, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(518, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 3, 1, 1)
        self.pushButtonCat_Clear = QtGui.QPushButton(self.layoutWidget1)
        self.pushButtonCat_Clear.setObjectName("pushButtonCat_Clear")
        self.gridLayout_5.addWidget(self.pushButtonCat_Clear, 0, 4, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.line_16 = QtGui.QFrame(self.layoutWidget1)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_6.addWidget(self.line_16)
        self.tableWidgetCat = QtGui.QTableWidget(self.layoutWidget1)
        self.tableWidgetCat.setLineWidth(2)
        self.tableWidgetCat.setRowCount(0)
        self.tableWidgetCat.setObjectName("tableWidgetCat")
        self.tableWidgetCat.setColumnCount(10)
        self.tableWidgetCat.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCat.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCat.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCat.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCat.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCat.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCat.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCat.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCat.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCat.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCat.setHorizontalHeaderItem(9, item)
        self.verticalLayout_6.addWidget(self.tableWidgetCat)
        self.tabWidget.addTab(self.CatTab, "")
        self.SlitsTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SlitsTab.sizePolicy().hasHeightForWidth())
        self.SlitsTab.setSizePolicy(sizePolicy)
        self.SlitsTab.setObjectName("SlitsTab")
        self.labelSlit_Infotext_2 = QtGui.QLabel(self.SlitsTab)
        self.labelSlit_Infotext_2.setGeometry(QtCore.QRect(10, 20, 567, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.labelSlit_Infotext_2.setFont(font)
        self.labelSlit_Infotext_2.setObjectName("labelSlit_Infotext_2")
        self.layoutWidget2 = QtGui.QWidget(self.SlitsTab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 48, 1081, 471))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_10 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelSlit_ImportCat = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelSlit_ImportCat.setFont(font)
        self.labelSlit_ImportCat.setObjectName("labelSlit_ImportCat")
        self.gridLayout_4.addWidget(self.labelSlit_ImportCat, 0, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.layoutWidget2)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 0, 1, 3, 1)
        self.labelSlit_ManEdit = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelSlit_ManEdit.setFont(font)
        self.labelSlit_ManEdit.setObjectName("labelSlit_ManEdit")
        self.gridLayout_4.addWidget(self.labelSlit_ManEdit, 0, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 3, 1, 1)
        self.line_7 = QtGui.QFrame(self.layoutWidget2)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_4.addWidget(self.line_7, 0, 4, 3, 1)
        self.labelSlit_ManEditImage = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelSlit_ManEditImage.setFont(font)
        self.labelSlit_ManEditImage.setObjectName("labelSlit_ManEditImage")
        self.gridLayout_4.addWidget(self.labelSlit_ManEditImage, 0, 5, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(90, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 6, 1, 1)
        self.line_8 = QtGui.QFrame(self.layoutWidget2)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_4.addWidget(self.line_8, 0, 7, 3, 1)
        self.pushButtonSlit_AddSlitImage = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_AddSlitImage.setObjectName("pushButtonSlit_AddSlitImage")
        self.gridLayout_4.addWidget(self.pushButtonSlit_AddSlitImage, 1, 5, 2, 1)
        self.pushButtonSlit_DeleteSlitImage = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_DeleteSlitImage.setObjectName("pushButtonSlit_DeleteSlitImage")
        self.gridLayout_4.addWidget(self.pushButtonSlit_DeleteSlitImage, 1, 6, 2, 1)
        self.pushButtonSlit_ClearSlits = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_ClearSlits.setObjectName("pushButtonSlit_ClearSlits")
        self.gridLayout_4.addWidget(self.pushButtonSlit_ClearSlits, 1, 8, 2, 1)
        self.pushButtonSlit_AddSlitfromCat = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_AddSlitfromCat.setObjectName("pushButtonSlit_AddSlitfromCat")
        self.gridLayout_4.addWidget(self.pushButtonSlit_AddSlitfromCat, 1, 0, 2, 1)
        self.pushButtonSlit_AddSlit = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_AddSlit.setObjectName("pushButtonSlit_AddSlit")
        self.gridLayout_4.addWidget(self.pushButtonSlit_AddSlit, 1, 2, 2, 1)
        self.pushButtonSlit_DeleteSlit = QtGui.QPushButton(self.layoutWidget2)
        self.pushButtonSlit_DeleteSlit.setObjectName("pushButtonSlit_DeleteSlit")
        self.gridLayout_4.addWidget(self.pushButtonSlit_DeleteSlit, 1, 3, 2, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tableWidgetSlits = QtGui.QTableWidget(self.layoutWidget2)
        self.tableWidgetSlits.setLineWidth(2)
        self.tableWidgetSlits.setRowCount(0)
        self.tableWidgetSlits.setObjectName("tableWidgetSlits")
        self.tableWidgetSlits.setColumnCount(10)
        self.tableWidgetSlits.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSlits.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSlits.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSlits.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSlits.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSlits.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSlits.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSlits.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSlits.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSlits.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSlits.setHorizontalHeaderItem(9, item)
        self.gridLayout_10.addWidget(self.tableWidgetSlits, 2, 0, 1, 1)
        self.line_14 = QtGui.QFrame(self.layoutWidget2)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_10.addWidget(self.line_14, 1, 0, 1, 1)
        self.tabWidget.addTab(self.SlitsTab, "")
        self.OptimizeTab = QtGui.QWidget()
        self.OptimizeTab.setObjectName("OptimizeTab")
        self.checkBoxOpt_Extendslits = QtGui.QCheckBox(self.OptimizeTab)
        self.checkBoxOpt_Extendslits.setEnabled(False)
        self.checkBoxOpt_Extendslits.setGeometry(QtCore.QRect(10, 190, 111, 22))
        self.checkBoxOpt_Extendslits.setObjectName("checkBoxOpt_Extendslits")
        self.checkBoxOpt_IncRefstars = QtGui.QCheckBox(self.OptimizeTab)
        self.checkBoxOpt_IncRefstars.setGeometry(QtCore.QRect(10, 220, 131, 22))
        self.checkBoxOpt_IncRefstars.setObjectName("checkBoxOpt_IncRefstars")
        self.labelOpt_Refstarstext_2 = QtGui.QLabel(self.OptimizeTab)
        self.labelOpt_Refstarstext_2.setEnabled(False)
        self.labelOpt_Refstarstext_2.setGeometry(QtCore.QRect(140, 280, 101, 17))
        self.labelOpt_Refstarstext_2.setObjectName("labelOpt_Refstarstext_2")
        self.lineEditOpt_NumRefstars = QtGui.QLineEdit(self.OptimizeTab)
        self.lineEditOpt_NumRefstars.setEnabled(False)
        self.lineEditOpt_NumRefstars.setGeometry(QtCore.QRect(100, 270, 31, 27))
        self.lineEditOpt_NumRefstars.setObjectName("lineEditOpt_NumRefstars")
        self.labelOpt_Refstarstext_1 = QtGui.QLabel(self.OptimizeTab)
        self.labelOpt_Refstarstext_1.setEnabled(False)
        self.labelOpt_Refstarstext_1.setGeometry(QtCore.QRect(30, 280, 71, 17))
        self.labelOpt_Refstarstext_1.setObjectName("labelOpt_Refstarstext_1")
        self.lineEditOpt_AllRefstars = QtGui.QLineEdit(self.OptimizeTab)
        self.lineEditOpt_AllRefstars.setEnabled(False)
        self.lineEditOpt_AllRefstars.setGeometry(QtCore.QRect(230, 270, 31, 27))
        self.lineEditOpt_AllRefstars.setReadOnly(True)
        self.lineEditOpt_AllRefstars.setObjectName("lineEditOpt_AllRefstars")
        self.labelOpt_Refstarstest_3 = QtGui.QLabel(self.OptimizeTab)
        self.labelOpt_Refstarstest_3.setEnabled(False)
        self.labelOpt_Refstarstest_3.setGeometry(QtCore.QRect(270, 280, 91, 17))
        self.labelOpt_Refstarstest_3.setObjectName("labelOpt_Refstarstest_3")
        self.labelOpt_Refstarstext = QtGui.QLabel(self.OptimizeTab)
        self.labelOpt_Refstarstext.setEnabled(False)
        self.labelOpt_Refstarstext.setGeometry(QtCore.QRect(30, 250, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelOpt_Refstarstext.setFont(font)
        self.labelOpt_Refstarstext.setObjectName("labelOpt_Refstarstext")
        self.checkBoxOpt_SpecifyWavRange = QtGui.QCheckBox(self.OptimizeTab)
        self.checkBoxOpt_SpecifyWavRange.setEnabled(False)
        self.checkBoxOpt_SpecifyWavRange.setGeometry(QtCore.QRect(10, 320, 201, 22))
        self.checkBoxOpt_SpecifyWavRange.setObjectName("checkBoxOpt_SpecifyWavRange")
        self.labelOpt_RSSSetuptext_1 = QtGui.QLabel(self.OptimizeTab)
        self.labelOpt_RSSSetuptext_1.setEnabled(False)
        self.labelOpt_RSSSetuptext_1.setGeometry(QtCore.QRect(30, 350, 351, 17))
        self.labelOpt_RSSSetuptext_1.setObjectName("labelOpt_RSSSetuptext_1")
        self.lineEditOpt_RSSStartWav = QtGui.QLineEdit(self.OptimizeTab)
        self.lineEditOpt_RSSStartWav.setEnabled(False)
        self.lineEditOpt_RSSStartWav.setGeometry(QtCore.QRect(380, 340, 91, 27))
        self.lineEditOpt_RSSStartWav.setObjectName("lineEditOpt_RSSStartWav")
        self.labelOpt_RSSSetuptext_2 = QtGui.QLabel(self.OptimizeTab)
        self.labelOpt_RSSSetuptext_2.setEnabled(False)
        self.labelOpt_RSSSetuptext_2.setGeometry(QtCore.QRect(480, 350, 51, 17))
        self.labelOpt_RSSSetuptext_2.setObjectName("labelOpt_RSSSetuptext_2")
        self.lineEditOpt_RSSEndWav = QtGui.QLineEdit(self.OptimizeTab)
        self.lineEditOpt_RSSEndWav.setEnabled(False)
        self.lineEditOpt_RSSEndWav.setGeometry(QtCore.QRect(530, 340, 91, 27))
        self.lineEditOpt_RSSEndWav.setObjectName("lineEditOpt_RSSEndWav")
        self.labelOpt_RSSSetuptext_3 = QtGui.QLabel(self.OptimizeTab)
        self.labelOpt_RSSSetuptext_3.setEnabled(False)
        self.labelOpt_RSSSetuptext_3.setGeometry(QtCore.QRect(630, 350, 31, 17))
        self.labelOpt_RSSSetuptext_3.setObjectName("labelOpt_RSSSetuptext_3")
        self.labelOpt_Desiredtext = QtGui.QLabel(self.OptimizeTab)
        self.labelOpt_Desiredtext.setEnabled(False)
        self.labelOpt_Desiredtext.setGeometry(QtCore.QRect(30, 380, 351, 17))
        self.labelOpt_Desiredtext.setObjectName("labelOpt_Desiredtext")
        self.lineEditOpt_DesiredStartWav = QtGui.QLineEdit(self.OptimizeTab)
        self.lineEditOpt_DesiredStartWav.setEnabled(False)
        self.lineEditOpt_DesiredStartWav.setGeometry(QtCore.QRect(380, 370, 91, 27))
        self.lineEditOpt_DesiredStartWav.setObjectName("lineEditOpt_DesiredStartWav")
        self.lineEditOpt_DesiredEndWav = QtGui.QLineEdit(self.OptimizeTab)
        self.lineEditOpt_DesiredEndWav.setEnabled(False)
        self.lineEditOpt_DesiredEndWav.setGeometry(QtCore.QRect(530, 370, 91, 27))
        self.lineEditOpt_DesiredEndWav.setObjectName("lineEditOpt_DesiredEndWav")
        self.labelOpt_Desiredtext_1 = QtGui.QLabel(self.OptimizeTab)
        self.labelOpt_Desiredtext_1.setEnabled(False)
        self.labelOpt_Desiredtext_1.setGeometry(QtCore.QRect(480, 380, 51, 17))
        self.labelOpt_Desiredtext_1.setObjectName("labelOpt_Desiredtext_1")
        self.labelOpt_Desiredtext_2 = QtGui.QLabel(self.OptimizeTab)
        self.labelOpt_Desiredtext_2.setEnabled(False)
        self.labelOpt_Desiredtext_2.setGeometry(QtCore.QRect(630, 380, 31, 17))
        self.labelOpt_Desiredtext_2.setObjectName("labelOpt_Desiredtext_2")
        self.layoutWidget3 = QtGui.QWidget(self.OptimizeTab)
        self.layoutWidget3.setGeometry(QtCore.QRect(21, 80, 151, 95))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayoutOpt = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayoutOpt.setObjectName("gridLayoutOpt")
        self.labelOpt_Xspacing = QtGui.QLabel(self.layoutWidget3)
        self.labelOpt_Xspacing.setEnabled(False)
        self.labelOpt_Xspacing.setObjectName("labelOpt_Xspacing")
        self.gridLayoutOpt.addWidget(self.labelOpt_Xspacing, 0, 0, 1, 1)
        self.lineEditOpt_Xspacing = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEditOpt_Xspacing.setEnabled(False)
        self.lineEditOpt_Xspacing.setObjectName("lineEditOpt_Xspacing")
        self.gridLayoutOpt.addWidget(self.lineEditOpt_Xspacing, 0, 1, 1, 1)
        self.labelOpt_Xarcsec = QtGui.QLabel(self.layoutWidget3)
        self.labelOpt_Xarcsec.setObjectName("labelOpt_Xarcsec")
        self.gridLayoutOpt.addWidget(self.labelOpt_Xarcsec, 0, 2, 1, 1)
        self.labelOpt_Yspacing = QtGui.QLabel(self.layoutWidget3)
        self.labelOpt_Yspacing.setObjectName("labelOpt_Yspacing")
        self.gridLayoutOpt.addWidget(self.labelOpt_Yspacing, 1, 0, 1, 1)
        self.lineEditOpt_Yspacing = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEditOpt_Yspacing.setObjectName("lineEditOpt_Yspacing")
        self.gridLayoutOpt.addWidget(self.lineEditOpt_Yspacing, 1, 1, 1, 1)
        self.labelOpt_Yarcsec = QtGui.QLabel(self.layoutWidget3)
        self.labelOpt_Yarcsec.setObjectName("labelOpt_Yarcsec")
        self.gridLayoutOpt.addWidget(self.labelOpt_Yarcsec, 1, 2, 1, 1)
        self.labelOpt_Niter = QtGui.QLabel(self.layoutWidget3)
        self.labelOpt_Niter.setObjectName("labelOpt_Niter")
        self.gridLayoutOpt.addWidget(self.labelOpt_Niter, 2, 0, 1, 1)
        self.lineEditOpt_Niter = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEditOpt_Niter.setObjectName("lineEditOpt_Niter")
        self.gridLayoutOpt.addWidget(self.lineEditOpt_Niter, 2, 1, 1, 1)
        self.pushButtonOpt_Optimize = QtGui.QPushButton(self.OptimizeTab)
        self.pushButtonOpt_Optimize.setGeometry(QtCore.QRect(20, 30, 93, 27))
        self.pushButtonOpt_Optimize.setObjectName("pushButtonOpt_Optimize")
        self.tabWidget.addTab(self.OptimizeTab, "")
        self.RefstarsTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RefstarsTab.sizePolicy().hasHeightForWidth())
        self.RefstarsTab.setSizePolicy(sizePolicy)
        self.RefstarsTab.setObjectName("RefstarsTab")
        self.layoutWidget4 = QtGui.QWidget(self.RefstarsTab)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 11, 1081, 511))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_11 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelRef_ImportCat = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelRef_ImportCat.setFont(font)
        self.labelRef_ImportCat.setObjectName("labelRef_ImportCat")
        self.gridLayout_3.addWidget(self.labelRef_ImportCat, 0, 0, 1, 1)
        self.lineRef_line2 = QtGui.QFrame(self.layoutWidget4)
        self.lineRef_line2.setFrameShape(QtGui.QFrame.VLine)
        self.lineRef_line2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineRef_line2.setObjectName("lineRef_line2")
        self.gridLayout_3.addWidget(self.lineRef_line2, 0, 1, 3, 1)
        self.labelRef_ManEdit = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelRef_ManEdit.setFont(font)
        self.labelRef_ManEdit.setObjectName("labelRef_ManEdit")
        self.gridLayout_3.addWidget(self.labelRef_ManEdit, 0, 2, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 3, 1, 1)
        self.lineRef_line1 = QtGui.QFrame(self.layoutWidget4)
        self.lineRef_line1.setFrameShape(QtGui.QFrame.VLine)
        self.lineRef_line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineRef_line1.setObjectName("lineRef_line1")
        self.gridLayout_3.addWidget(self.lineRef_line1, 0, 4, 3, 1)
        self.labelRef_ManEditImage = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelRef_ManEditImage.setFont(font)
        self.labelRef_ManEditImage.setObjectName("labelRef_ManEditImage")
        self.gridLayout_3.addWidget(self.labelRef_ManEditImage, 0, 5, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 0, 6, 1, 1)
        self.lineRef_line1_2 = QtGui.QFrame(self.layoutWidget4)
        self.lineRef_line1_2.setFrameShape(QtGui.QFrame.VLine)
        self.lineRef_line1_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineRef_line1_2.setObjectName("lineRef_line1_2")
        self.gridLayout_3.addWidget(self.lineRef_line1_2, 0, 7, 3, 1)
        self.pushButtonRef_ClearRefstars = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_ClearRefstars.setObjectName("pushButtonRef_ClearRefstars")
        self.gridLayout_3.addWidget(self.pushButtonRef_ClearRefstars, 1, 8, 2, 1)
        self.pushButtonRef_AddRefstarsfromCat = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_AddRefstarsfromCat.setObjectName("pushButtonRef_AddRefstarsfromCat")
        self.gridLayout_3.addWidget(self.pushButtonRef_AddRefstarsfromCat, 2, 0, 1, 1)
        self.pushButtonRef_AddRefstar = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_AddRefstar.setObjectName("pushButtonRef_AddRefstar")
        self.gridLayout_3.addWidget(self.pushButtonRef_AddRefstar, 2, 2, 1, 1)
        self.pushButtonRef_DeleteRefstar = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_DeleteRefstar.setObjectName("pushButtonRef_DeleteRefstar")
        self.gridLayout_3.addWidget(self.pushButtonRef_DeleteRefstar, 2, 3, 1, 1)
        self.pushButtonRef_AddRefstarImage = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_AddRefstarImage.setObjectName("pushButtonRef_AddRefstarImage")
        self.gridLayout_3.addWidget(self.pushButtonRef_AddRefstarImage, 2, 5, 1, 1)
        self.pushButtonRef_DeleteRefstar_2 = QtGui.QPushButton(self.layoutWidget4)
        self.pushButtonRef_DeleteRefstar_2.setObjectName("pushButtonRef_DeleteRefstar_2")
        self.gridLayout_3.addWidget(self.pushButtonRef_DeleteRefstar_2, 2, 6, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tableWidgetRefstars = QtGui.QTableWidget(self.layoutWidget4)
        self.tableWidgetRefstars.setLineWidth(2)
        self.tableWidgetRefstars.setRowCount(0)
        self.tableWidgetRefstars.setObjectName("tableWidgetRefstars")
        self.tableWidgetRefstars.setColumnCount(10)
        self.tableWidgetRefstars.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRefstars.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRefstars.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRefstars.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRefstars.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRefstars.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRefstars.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRefstars.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRefstars.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRefstars.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetRefstars.setHorizontalHeaderItem(9, item)
        self.gridLayout_11.addWidget(self.tableWidgetRefstars, 2, 0, 1, 1)
        self.line_15 = QtGui.QFrame(self.layoutWidget4)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_11.addWidget(self.line_15, 1, 0, 1, 1)
        self.tabWidget.addTab(self.RefstarsTab, "")
        self.FinalizeTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FinalizeTab.sizePolicy().hasHeightForWidth())
        self.FinalizeTab.setSizePolicy(sizePolicy)
        self.FinalizeTab.setObjectName("FinalizeTab")
        self.textEditFin_ErrorMessages = QtGui.QTextEdit(self.FinalizeTab)
        self.textEditFin_ErrorMessages.setEnabled(True)
        self.textEditFin_ErrorMessages.setGeometry(QtCore.QRect(510, 10, 531, 261))
        self.textEditFin_ErrorMessages.setAutoFillBackground(True)
        self.textEditFin_ErrorMessages.setFrameShadow(QtGui.QFrame.Plain)
        self.textEditFin_ErrorMessages.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEditFin_ErrorMessages.setObjectName("textEditFin_ErrorMessages")
        self.layoutWidget5 = QtGui.QWidget(self.FinalizeTab)
        self.layoutWidget5.setGeometry(QtCore.QRect(9, 11, 492, 253))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_19 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.labelFin_Slitmask = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelFin_Slitmask.setFont(font)
        self.labelFin_Slitmask.setObjectName("labelFin_Slitmask")
        self.gridLayout_19.addWidget(self.labelFin_Slitmask, 0, 0, 1, 1)
        self.pushButtonFin_Validate = QtGui.QPushButton(self.layoutWidget5)
        self.pushButtonFin_Validate.setObjectName("pushButtonFin_Validate")
        self.gridLayout_19.addWidget(self.pushButtonFin_Validate, 1, 0, 1, 1)
        self.toolButtonFin_WriteRSMT = QtGui.QToolButton(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonFin_WriteRSMT.sizePolicy().hasHeightForWidth())
        self.toolButtonFin_WriteRSMT.setSizePolicy(sizePolicy)
        self.toolButtonFin_WriteRSMT.setObjectName("toolButtonFin_WriteRSMT")
        self.gridLayout_19.addWidget(self.toolButtonFin_WriteRSMT, 2, 0, 1, 1)
        self.labelFin_WriteRSMTinfo = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setItalic(True)
        self.labelFin_WriteRSMTinfo.setFont(font)
        self.labelFin_WriteRSMTinfo.setObjectName("labelFin_WriteRSMTinfo")
        self.gridLayout_19.addWidget(self.labelFin_WriteRSMTinfo, 2, 1, 1, 1)
        self.lineFin_3 = QtGui.QFrame(self.layoutWidget5)
        self.lineFin_3.setFrameShape(QtGui.QFrame.HLine)
        self.lineFin_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineFin_3.setObjectName("lineFin_3")
        self.gridLayout_19.addWidget(self.lineFin_3, 3, 0, 1, 3)
        self.labelFin_FChart_3 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelFin_FChart_3.setFont(font)
        self.labelFin_FChart_3.setObjectName("labelFin_FChart_3")
        self.gridLayout_19.addWidget(self.labelFin_FChart_3, 4, 0, 1, 1)
        self.pushButtonFin_WriteXML = QtGui.QPushButton(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFin_WriteXML.sizePolicy().hasHeightForWidth())
        self.pushButtonFin_WriteXML.setSizePolicy(sizePolicy)
        self.pushButtonFin_WriteXML.setObjectName("pushButtonFin_WriteXML")
        self.gridLayout_19.addWidget(self.pushButtonFin_WriteXML, 5, 0, 1, 1)
        self.lineFin = QtGui.QFrame(self.layoutWidget5)
        self.lineFin.setFrameShape(QtGui.QFrame.HLine)
        self.lineFin.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineFin.setObjectName("lineFin")
        self.gridLayout_19.addWidget(self.lineFin, 6, 0, 1, 3)
        self.labelFin_FChart = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelFin_FChart.setFont(font)
        self.labelFin_FChart.setObjectName("labelFin_FChart")
        self.gridLayout_19.addWidget(self.labelFin_FChart, 7, 0, 1, 1)
        self.pushButtonFin_CreateFChart_Current = QtGui.QPushButton(self.layoutWidget5)
        self.pushButtonFin_CreateFChart_Current.setObjectName("pushButtonFin_CreateFChart_Current")
        self.gridLayout_19.addWidget(self.pushButtonFin_CreateFChart_Current, 8, 0, 1, 2)
        self.pushButtonFin_CreateFChart_DSS = QtGui.QPushButton(self.layoutWidget5)
        self.pushButtonFin_CreateFChart_DSS.setObjectName("pushButtonFin_CreateFChart_DSS")
        self.gridLayout_19.addWidget(self.pushButtonFin_CreateFChart_DSS, 9, 0, 1, 2)
        self.labelFin_CreateFChartinfo = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setItalic(True)
        self.labelFin_CreateFChartinfo.setFont(font)
        self.labelFin_CreateFChartinfo.setObjectName("labelFin_CreateFChartinfo")
        self.gridLayout_19.addWidget(self.labelFin_CreateFChartinfo, 9, 2, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem11, 4, 2, 1, 1)
        self.tabWidget.addTab(self.FinalizeTab, "")
        self.line_10 = QtGui.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(9, 198, 1051, 16))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(420, 10, 16, 183))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layoutWidget6 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(510, 20, 511, 175))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutMain_MaskCoords = QtGui.QVBoxLayout()
        self.verticalLayoutMain_MaskCoords.setObjectName("verticalLayoutMain_MaskCoords")
        self.labelMain_MaskHeading = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.labelMain_MaskHeading.setFont(font)
        self.labelMain_MaskHeading.setObjectName("labelMain_MaskHeading")
        self.verticalLayoutMain_MaskCoords.addWidget(self.labelMain_MaskHeading)
        self.gridLayoutMain_MaskCoords = QtGui.QGridLayout()
        self.gridLayoutMain_MaskCoords.setObjectName("gridLayoutMain_MaskCoords")
        self.labelMain_CenRA = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_CenRA.setFont(font)
        self.labelMain_CenRA.setObjectName("labelMain_CenRA")
        self.gridLayoutMain_MaskCoords.addWidget(self.labelMain_CenRA, 0, 0, 1, 1)
        self.labelMain_CenDEC = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_CenDEC.setFont(font)
        self.labelMain_CenDEC.setObjectName("labelMain_CenDEC")
        self.gridLayoutMain_MaskCoords.addWidget(self.labelMain_CenDEC, 0, 1, 1, 1)
        self.labelMain_Epoch = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_Epoch.setFont(font)
        self.labelMain_Epoch.setObjectName("labelMain_Epoch")
        self.gridLayoutMain_MaskCoords.addWidget(self.labelMain_Epoch, 0, 2, 1, 1)
        self.labelMain_PA = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_PA.setFont(font)
        self.labelMain_PA.setObjectName("labelMain_PA")
        self.gridLayoutMain_MaskCoords.addWidget(self.labelMain_PA, 0, 3, 1, 1)
        self.lineEditMain_CenRA = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_CenRA.setObjectName("lineEditMain_CenRA")
        self.gridLayoutMain_MaskCoords.addWidget(self.lineEditMain_CenRA, 1, 0, 1, 1)
        self.lineEditMain_CenDEC = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_CenDEC.setText("")
        self.lineEditMain_CenDEC.setObjectName("lineEditMain_CenDEC")
        self.gridLayoutMain_MaskCoords.addWidget(self.lineEditMain_CenDEC, 1, 1, 1, 1)
        self.lineEditMain_Equinox = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_Equinox.setObjectName("lineEditMain_Equinox")
        self.gridLayoutMain_MaskCoords.addWidget(self.lineEditMain_Equinox, 1, 2, 1, 1)
        self.lineEditMain_PA = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_PA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditMain_PA.setObjectName("lineEditMain_PA")
        self.gridLayoutMain_MaskCoords.addWidget(self.lineEditMain_PA, 1, 3, 1, 1)
        self.verticalLayoutMain_MaskCoords.addLayout(self.gridLayoutMain_MaskCoords)
        self.verticalLayout_2.addLayout(self.verticalLayoutMain_MaskCoords)
        self.line = QtGui.QFrame(self.layoutWidget6)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayoutMain_RSSSetup = QtGui.QVBoxLayout()
        self.verticalLayoutMain_RSSSetup.setObjectName("verticalLayoutMain_RSSSetup")
        self.labelMain_RSSHeading = QtGui.QLabel(self.layoutWidget6)
        self.labelMain_RSSHeading.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.labelMain_RSSHeading.setFont(font)
        self.labelMain_RSSHeading.setObjectName("labelMain_RSSHeading")
        self.verticalLayoutMain_RSSSetup.addWidget(self.labelMain_RSSHeading)
        self.gridLayoutMain_RSSSetup = QtGui.QGridLayout()
        self.gridLayoutMain_RSSSetup.setObjectName("gridLayoutMain_RSSSetup")
        self.labelMain_Filter = QtGui.QLabel(self.layoutWidget6)
        self.labelMain_Filter.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_Filter.setFont(font)
        self.labelMain_Filter.setObjectName("labelMain_Filter")
        self.gridLayoutMain_RSSSetup.addWidget(self.labelMain_Filter, 0, 0, 1, 1)
        self.labelMain_Grating = QtGui.QLabel(self.layoutWidget6)
        self.labelMain_Grating.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_Grating.setFont(font)
        self.labelMain_Grating.setObjectName("labelMain_Grating")
        self.gridLayoutMain_RSSSetup.addWidget(self.labelMain_Grating, 0, 1, 1, 1)
        self.labelMain_CamAng = QtGui.QLabel(self.layoutWidget6)
        self.labelMain_CamAng.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_CamAng.setFont(font)
        self.labelMain_CamAng.setObjectName("labelMain_CamAng")
        self.gridLayoutMain_RSSSetup.addWidget(self.labelMain_CamAng, 0, 2, 1, 1)
        self.labelMain_GrAng = QtGui.QLabel(self.layoutWidget6)
        self.labelMain_GrAng.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_GrAng.setFont(font)
        self.labelMain_GrAng.setObjectName("labelMain_GrAng")
        self.gridLayoutMain_RSSSetup.addWidget(self.labelMain_GrAng, 0, 3, 1, 1)
        self.lineEditMain_Filter = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_Filter.setEnabled(False)
        self.lineEditMain_Filter.setReadOnly(True)
        self.lineEditMain_Filter.setObjectName("lineEditMain_Filter")
        self.gridLayoutMain_RSSSetup.addWidget(self.lineEditMain_Filter, 1, 0, 1, 1)
        self.lineEditMain_Grating = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_Grating.setEnabled(False)
        self.lineEditMain_Grating.setText("")
        self.lineEditMain_Grating.setReadOnly(True)
        self.lineEditMain_Grating.setObjectName("lineEditMain_Grating")
        self.gridLayoutMain_RSSSetup.addWidget(self.lineEditMain_Grating, 1, 1, 1, 1)
        self.lineEditMain_CamAng = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_CamAng.setEnabled(False)
        self.lineEditMain_CamAng.setReadOnly(True)
        self.lineEditMain_CamAng.setObjectName("lineEditMain_CamAng")
        self.gridLayoutMain_RSSSetup.addWidget(self.lineEditMain_CamAng, 1, 2, 1, 1)
        self.lineEditMain_GrAng = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEditMain_GrAng.setEnabled(False)
        self.lineEditMain_GrAng.setReadOnly(True)
        self.lineEditMain_GrAng.setObjectName("lineEditMain_GrAng")
        self.gridLayoutMain_RSSSetup.addWidget(self.lineEditMain_GrAng, 1, 3, 1, 1)
        self.verticalLayoutMain_RSSSetup.addLayout(self.gridLayoutMain_RSSSetup)
        self.verticalLayout_2.addLayout(self.verticalLayoutMain_RSSSetup)
        self.layoutWidget7 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(21, 21, 301, 126))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayoutMain_Info = QtGui.QGridLayout()
        self.gridLayoutMain_Info.setObjectName("gridLayoutMain_Info")
        self.labelMain_TargetName = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_TargetName.setFont(font)
        self.labelMain_TargetName.setObjectName("labelMain_TargetName")
        self.gridLayoutMain_Info.addWidget(self.labelMain_TargetName, 0, 0, 1, 1)
        self.labelMain_MaskName = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_MaskName.setFont(font)
        self.labelMain_MaskName.setObjectName("labelMain_MaskName")
        self.gridLayoutMain_Info.addWidget(self.labelMain_MaskName, 2, 0, 1, 1)
        self.lineEditMain_MaskName = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEditMain_MaskName.setAutoFillBackground(False)
        self.lineEditMain_MaskName.setObjectName("lineEditMain_MaskName")
        self.gridLayoutMain_Info.addWidget(self.lineEditMain_MaskName, 2, 1, 1, 1)
        self.lineEditMain_TargetName = QtGui.QLineEdit(self.layoutWidget7)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEditMain_TargetName.setPalette(palette)
        self.lineEditMain_TargetName.setObjectName("lineEditMain_TargetName")
        self.gridLayoutMain_Info.addWidget(self.lineEditMain_TargetName, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayoutMain_Info)
        self.labelMain_Mode = QtGui.QLabel(self.layoutWidget7)
        self.labelMain_Mode.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_Mode.setFont(font)
        self.labelMain_Mode.setObjectName("labelMain_Mode")
        self.verticalLayout_5.addWidget(self.labelMain_Mode)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem12 = QtGui.QSpacerItem(90, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem12, 0, 1, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.labelMain_Centroiding = QtGui.QLabel(self.layoutWidget7)
        self.labelMain_Centroiding.setEnabled(False)
        self.labelMain_Centroiding.setObjectName("labelMain_Centroiding")
        self.gridLayout_7.addWidget(self.labelMain_Centroiding, 0, 1, 1, 1)
        self.labelMain_CentroidingOnOff = QtGui.QLabel(self.layoutWidget7)
        self.labelMain_CentroidingOnOff.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.labelMain_CentroidingOnOff.setFont(font)
        self.labelMain_CentroidingOnOff.setObjectName("labelMain_CentroidingOnOff")
        self.gridLayout_7.addWidget(self.labelMain_CentroidingOnOff, 0, 2, 1, 1)
        self.lineEditMain_Mode = QtGui.QLineEdit(self.layoutWidget7)
        self.lineEditMain_Mode.setEnabled(False)
        self.lineEditMain_Mode.setReadOnly(True)
        self.lineEditMain_Mode.setObjectName("lineEditMain_Mode")
        self.gridLayout_7.addWidget(self.lineEditMain_Mode, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLoad_Catalogue = QtGui.QAction(MainWindow)
        self.actionLoad_Catalogue.setObjectName("actionLoad_Catalogue")
        self.actionLoad_Image = QtGui.QAction(MainWindow)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOnline_user_manual = QtGui.QAction(MainWindow)
        self.actionOnline_user_manual.setObjectName("actionOnline_user_manual")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoad_Image)
        self.menuFile.addAction(self.actionLoad_Catalogue)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionOnline_user_manual)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.labelInfo_Proposer.setBuddy(self.lineEditInfo_Proposer)
        self.labelInfo_Creator.setBuddy(self.lineEditInfo_Creator)
        self.labelInfo_Filter.setBuddy(self.comboBoxInfo_Filter)
        self.labelInfo_Grating.setBuddy(self.comboBoxInfo_Grating)
        self.labelInfo_CamAng.setBuddy(self.horizontalSliderInfo_CamAng)
        self.labelInfo_GrAng.setBuddy(self.horizontalSliderInfo_CamAng)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QObject.connect(self.checkBoxOpt_IncRefstars, QtCore.SIGNAL("clicked(bool)"), self.labelOpt_Refstarstext.setEnabled)
        QtCore.QObject.connect(self.checkBoxOpt_IncRefstars, QtCore.SIGNAL("clicked(bool)"), self.labelOpt_Refstarstext_1.setEnabled)
        QtCore.QObject.connect(self.checkBoxOpt_IncRefstars, QtCore.SIGNAL("clicked(bool)"), self.lineEditOpt_NumRefstars.setEnabled)
        QtCore.QObject.connect(self.checkBoxOpt_IncRefstars, QtCore.SIGNAL("clicked(bool)"), self.labelOpt_Refstarstext_2.setEnabled)
        QtCore.QObject.connect(self.checkBoxOpt_IncRefstars, QtCore.SIGNAL("clicked(bool)"), self.lineEditOpt_AllRefstars.setEnabled)
        QtCore.QObject.connect(self.checkBoxOpt_IncRefstars, QtCore.SIGNAL("clicked(bool)"), self.labelOpt_Refstarstest_3.setEnabled)
        QtCore.QObject.connect(self.radioButtonInfo_Catalogue, QtCore.SIGNAL("clicked(bool)"), self.toolButtonCat_Load.setEnabled)
        QtCore.QObject.connect(self.radioButtonInfo_Manual, QtCore.SIGNAL("clicked(bool)"), self.toolButtonCat_Load.setDisabled)
        QtCore.QObject.connect(self.comboBoxInfo_Filter, QtCore.SIGNAL("activated(QString)"), self.lineEditMain_Filter.setText)
        QtCore.QObject.connect(self.comboBoxInfo_Grating, QtCore.SIGNAL("activated(QString)"), self.lineEditMain_Grating.setText)
        QtCore.QObject.connect(self.lineEditInfo_CamAng, QtCore.SIGNAL("textChanged(QString)"), self.lineEditMain_CamAng.setText)
        QtCore.QObject.connect(self.lineEditInfo_GrAng, QtCore.SIGNAL("textChanged(QString)"), self.lineEditInfo_GrAng.setText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "pySlitMask", None, QtGui.QApplication.UnicodeUTF8))
        self.textEditInstructions.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0055ff;\">pySlitMask:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:12pt; font-weight:600; text-decoration: underline; color:#0055ff;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">This is a quick start guide to design a MOS mask for the RSS on SALT. This tool was designed to be used with object catalogues. A full manual mode is not supported yet. It is therefore strongly recommended that a catalogue of target objects be created before using this tool. The tool makes use of a priority based optimization, this should be kept in mind when creating the input catalogue.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; text-decoration: underline;\">Preparation:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">1. Check the allowed position angle for the field:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">    </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-style:italic;\">http://www.salt.ac.za/fileadmin/files/observing/documents/SALT_PA_Visibility.pdf</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">2. Prepare an image of the field with accurate astrometry. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">3. Prepare an input catalogue of target objects</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">    The input catalogue should be an ascii file with the following formatting:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; font-style:italic;\">id  RA  DEC  epoch  magnitude  band  priority  [width]*  [length]*  [tilt]*</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt; font-weight:600; font-style:italic;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">*</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"> these are optional and can be updated in the tool. We currently suggest a minimum width of 1.5&quot; and a minimum length of 8&quot;. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">The priority should have the following values:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">    1      Object that is pre-selected to be in the mask</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">    0-1   Objects with increasing priority for the mask</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">   -1      Alignment star</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; text-decoration: underline;\">Step 1: Fill in Mask Details</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">. Fill in the Target and Mask name on the main window as well as the proposal information in the Info tab.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; text-decoration: underline;\">Step 2: Load Image and Catalogue</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">. Load the image of the field. </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-style:italic;\">File -&gt; Load Image</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">. Load the input catalogue of target objects. </span><span style=\" font-family:\'Sans\'; font-size:10pt; font-style:italic;\">File -&gt; Load Catalogue</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">. Update the Coordinates of the Mask Centre. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">. Ensure the Position Angle is correct.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Upon loading the catalogue into the tool, the Coordinates of the Mask Centre are populated with the mean RA and DEC values from the catalogue and a FoV check is run on all the objects in the catalogue. Objects assinged a priority of 1 will automatically be added to the Slit tab and will be checked for slit collisions. If any collisions were detected, they will be given in the Flags column in the table. Any obvious collisions can be resolved by deleting objects from the Slit table. Updating the Mask Centre Coordinates will automatically rerun the FoV checker.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; text-decoration: underline;\">Step 3: Optimize the Mask</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">. Go to the Optimize tab</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">. Set the Y spacing in arseconds if needed, the default is 1\'\'. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">. Run the optimizer</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The optimizer runs on all the target objects that lie within the RSS FoV. The optimizer will try and place as many slits on objects as possible while taking the priority into account. Currently, the tool will remove objects with a priority of 1 when a slit collision is detected. Objects to be in the mask can be inspected in the Slit table. Reference/alignment stars can be inspected in the Refstars tab. If there are undesired objects in the slit table it is recommended that their priority be updated (lowered) and the optimizer be run again. This procedure can be repeated until a suitable mask is obtained. The same applies to removing colliding/unwanted reference stars.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; text-decoration: underline;\">Step 4: Validate the Mask</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">. Go to the Finalize tab.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To be able to write the final .rsmt file required by the PIPT, the mask needs to be validated. The Validate button will go through and check whether all the relevant information has been filled in and will produce errors and warnings. Masks cannot be written to file when errors have been encountered. Note that the Validator does not check the Position Angle information.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt; font-weight:600; text-decoration: underline;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; text-decoration: underline;\">Step 5: Write .rsmt file</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">When the mask has been successfully validated, the mask  can be written to file. Hit the <span style=\" font-style:italic;\">Write .rsmt file</span> button. If the mask was not validated an error message will appear. The .rsmt file is a .zip format file containing a .xml file with the slit information and a finding chart in .png format.  </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; text-decoration: underline;\">Notes:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">. To add slits to objects using the ds9 interface, click on the objects of interest, which will create a region. Then click on the import from image Add slit button on the Slit tab. NOTE: the requested object needs to be loaded in the catalogue. The closest object in the catalogue from the added region will be assiged a slit. No object detection is implemented.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">. A mask can be saved and open later by saving it as a xml file.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">. Greyed out text and check boxes are space holders for future features.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">. Currently there are now checks whether a suitable guide star is available in the field. It is the responsibility of the PI to ensure that a suitable guide star is available to ensure the successful completion of the observation.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt; font-weight:600;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:9pt; font-style:italic; color:#000000;\">For queries please email: </span><a href=\"https://sciencewiki.salt.ac.za/index.php/PySlitMask_Tutorial\n"
"\"><span style=\" text-decoration: underline; color:#0000ff;\">sa@salt.ac.za</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt; font-weight:600;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InstructionsTab), QtGui.QApplication.translate("MainWindow", "  I&nstructions  ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_Mode.setText(QtGui.QApplication.translate("MainWindow", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonInfo_Catalogue.setText(QtGui.QApplication.translate("MainWindow", "Catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonInfo_Manual.setText(QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxInfo_CentroidOn.setText(QtGui.QApplication.translate("MainWindow", "Centroiding On", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_MaskInfo.setText(QtGui.QApplication.translate("MainWindow", "Mask Info:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_ProposalCode.setText(QtGui.QApplication.translate("MainWindow", "Proposal Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_Proposer.setText(QtGui.QApplication.translate("MainWindow", "PI:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_Creator.setText(QtGui.QApplication.translate("MainWindow", "Creator:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_RSSSetup.setText(QtGui.QApplication.translate("MainWindow", "RSS Setup:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_Filter.setText(QtGui.QApplication.translate("MainWindow", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Filter.setItemText(0, QtGui.QApplication.translate("MainWindow", "PC00000", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Filter.setItemText(1, QtGui.QApplication.translate("MainWindow", "PC03200", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Filter.setItemText(2, QtGui.QApplication.translate("MainWindow", "PC03400", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Filter.setItemText(3, QtGui.QApplication.translate("MainWindow", "PC03850", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Filter.setItemText(4, QtGui.QApplication.translate("MainWindow", "PC04600", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_Grating.setText(QtGui.QApplication.translate("MainWindow", "Grating:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(0, QtGui.QApplication.translate("MainWindow", "PG0300", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(1, QtGui.QApplication.translate("MainWindow", "PG0900", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(2, QtGui.QApplication.translate("MainWindow", "PG1300", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(3, QtGui.QApplication.translate("MainWindow", "PG1800", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(4, QtGui.QApplication.translate("MainWindow", "PG2300", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxInfo_Grating.setItemText(5, QtGui.QApplication.translate("MainWindow", "PG3000", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_CamAng.setText(QtGui.QApplication.translate("MainWindow", "Camera Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelInfo_GrAng.setText(QtGui.QApplication.translate("MainWindow", "Grating Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InfoTab), QtGui.QApplication.translate("MainWindow", "       &Info       ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCat_Infotext.setText(QtGui.QApplication.translate("MainWindow", "Input object catalogue. Only needed if Mode is set to Catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonCat_Load.setText(QtGui.QApplication.translate("MainWindow", "Load Catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCat_AddSlits.setText(QtGui.QApplication.translate("MainWindow", "Add Selected Slits", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCat_Clear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCat.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Object name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCat.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "RA", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCat.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "DEC", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCat.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCat.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Length1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCat.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Length2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCat.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCat.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Mag", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCat.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetCat.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "Flag", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CatTab), QtGui.QApplication.translate("MainWindow", "  &Catalogue  ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSlit_Infotext_2.setText(QtGui.QApplication.translate("MainWindow", "Slit collisionons may be resolved manually by editing the table below or automatically in the Optimize tab", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSlit_ImportCat.setText(QtGui.QApplication.translate("MainWindow", "Import from Catalogue:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSlit_ManEdit.setText(QtGui.QApplication.translate("MainWindow", "Manually edit slits:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSlit_ManEditImage.setText(QtGui.QApplication.translate("MainWindow", "Import from image", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_AddSlitImage.setText(QtGui.QApplication.translate("MainWindow", "Add slit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_DeleteSlitImage.setText(QtGui.QApplication.translate("MainWindow", "Delete slit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_ClearSlits.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_AddSlitfromCat.setText(QtGui.QApplication.translate("MainWindow", "Add slits to all catalogue objects", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_AddSlit.setText(QtGui.QApplication.translate("MainWindow", "Add slit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSlit_DeleteSlit.setText(QtGui.QApplication.translate("MainWindow", "Delete slit", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSlits.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Object name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSlits.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "RA", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSlits.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "DEC", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSlits.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSlits.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Length1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSlits.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Length2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSlits.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSlits.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Mag", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSlits.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetSlits.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "Flag", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SlitsTab), QtGui.QApplication.translate("MainWindow", "       &Slits       ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxOpt_Extendslits.setText(QtGui.QApplication.translate("MainWindow", "Extend slits", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxOpt_IncRefstars.setText(QtGui.QApplication.translate("MainWindow", "Include refstars", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Refstarstext_2.setText(QtGui.QApplication.translate("MainWindow", "refstars from ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Refstarstext_1.setText(QtGui.QApplication.translate("MainWindow", "Select N=", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Refstarstest_3.setText(QtGui.QApplication.translate("MainWindow", "in catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Refstarstext.setText(QtGui.QApplication.translate("MainWindow", "Num refstars:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxOpt_SpecifyWavRange.setText(QtGui.QApplication.translate("MainWindow", "Specify wavelength range", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_RSSSetuptext_1.setText(QtGui.QApplication.translate("MainWindow", "Maximum wavelength range with current RSS setup:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_RSSSetuptext_2.setText(QtGui.QApplication.translate("MainWindow", "Ang. to ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_RSSSetuptext_3.setText(QtGui.QApplication.translate("MainWindow", "Ang", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Desiredtext.setText(QtGui.QApplication.translate("MainWindow", "Desired wavelength range to fall on the detector: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Desiredtext_1.setText(QtGui.QApplication.translate("MainWindow", "Ang. to", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Desiredtext_2.setText(QtGui.QApplication.translate("MainWindow", "Ang", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Xspacing.setText(QtGui.QApplication.translate("MainWindow", "X spacing:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Xarcsec.setText(QtGui.QApplication.translate("MainWindow", "\'\'", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Yspacing.setText(QtGui.QApplication.translate("MainWindow", "Y spacing:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Yarcsec.setText(QtGui.QApplication.translate("MainWindow", "\'\'", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOpt_Niter.setText(QtGui.QApplication.translate("MainWindow", "N iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOpt_Optimize.setText(QtGui.QApplication.translate("MainWindow", "Optimize", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OptimizeTab), QtGui.QApplication.translate("MainWindow", "    &Optimize     ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRef_ImportCat.setText(QtGui.QApplication.translate("MainWindow", "Import from Catalogue:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRef_ManEdit.setText(QtGui.QApplication.translate("MainWindow", "Manually edit refstars:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRef_ManEditImage.setText(QtGui.QApplication.translate("MainWindow", "Import from image", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_ClearRefstars.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_AddRefstarsfromCat.setText(QtGui.QApplication.translate("MainWindow", "Add refstars from catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_AddRefstar.setText(QtGui.QApplication.translate("MainWindow", "Add refstar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_DeleteRefstar.setText(QtGui.QApplication.translate("MainWindow", "Delete refstar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_AddRefstarImage.setText(QtGui.QApplication.translate("MainWindow", "Add refstar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRef_DeleteRefstar_2.setText(QtGui.QApplication.translate("MainWindow", "Delete refstar", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRefstars.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Object name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRefstars.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "RA", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRefstars.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "DEC", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRefstars.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRefstars.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Length1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRefstars.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Length2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRefstars.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRefstars.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Mag", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRefstars.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRefstars.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("MainWindow", "Flag", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RefstarsTab), QtGui.QApplication.translate("MainWindow", "     &Refstars      ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFin_Slitmask.setText(QtGui.QApplication.translate("MainWindow", "Slitmask:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFin_Validate.setText(QtGui.QApplication.translate("MainWindow", "Validate", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonFin_WriteRSMT.setText(QtGui.QApplication.translate("MainWindow", "Write .rsmt file", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFin_WriteRSMTinfo.setText(QtGui.QApplication.translate("MainWindow", "file to load into PIPT", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFin_FChart_3.setText(QtGui.QApplication.translate("MainWindow", "XML Source", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFin_WriteXML.setText(QtGui.QApplication.translate("MainWindow", "Write XML Source", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFin_FChart.setText(QtGui.QApplication.translate("MainWindow", "Finder Chart:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFin_CreateFChart_Current.setText(QtGui.QApplication.translate("MainWindow", "Create Finder Chart from current image", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFin_CreateFChart_DSS.setText(QtGui.QApplication.translate("MainWindow", "Create finder chart from DSS image", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFin_CreateFChartinfo.setText(QtGui.QApplication.translate("MainWindow", "recommended for deep science images", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FinalizeTab), QtGui.QApplication.translate("MainWindow", "     &Finalize      ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_MaskHeading.setText(QtGui.QApplication.translate("MainWindow", "Coordinates of Mask Centre:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_CenRA.setText(QtGui.QApplication.translate("MainWindow", "Centre RA:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_CenDEC.setText(QtGui.QApplication.translate("MainWindow", "Centre DEC:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_Epoch.setText(QtGui.QApplication.translate("MainWindow", "Equinox:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_PA.setText(QtGui.QApplication.translate("MainWindow", "Positional Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_RSSHeading.setText(QtGui.QApplication.translate("MainWindow", "RSS Setup:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_Filter.setText(QtGui.QApplication.translate("MainWindow", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_Grating.setText(QtGui.QApplication.translate("MainWindow", "Grating:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_CamAng.setText(QtGui.QApplication.translate("MainWindow", "Camera Ang.:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_GrAng.setText(QtGui.QApplication.translate("MainWindow", "Grating Ang.:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_TargetName.setText(QtGui.QApplication.translate("MainWindow", "Target Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_MaskName.setText(QtGui.QApplication.translate("MainWindow", "Mask Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_Mode.setText(QtGui.QApplication.translate("MainWindow", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_Centroiding.setText(QtGui.QApplication.translate("MainWindow", "Centroiding:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMain_CentroidingOnOff.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Catalogue.setText(QtGui.QApplication.translate("MainWindow", "Load Catalogue", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Image.setText(QtGui.QApplication.translate("MainWindow", "Load Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOnline_user_manual.setText(QtGui.QApplication.translate("MainWindow", "Online user manual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

